project_id = "rgvvcbedockykchjwvth"

[functions.clerk-webhook]
verify_jwt = false

[functions.get-profile]
verify_jwt = false

[functions.update-profile]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.admin-get-users]
verify_jwt = false

[functions.ai-diagnosis]
verify_jwt = false

[functions.upload-r2]
verify_jwt = false

[functions.save-diagnosis]
verify_jwt = false

[functions.save-community-application]
verify_jwt = false

[functions.get-diagnoses]
verify_jwt = false
