project_id = "rgvvcbedockykchjwvth"

[functions.clerk-webhook]
verify_jwt = false

[functions.get-profile]
verify_jwt = false

[functions.update-profile]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.admin-get-users]
verify_jwt = false